platform:
  accel: "gpu"
  cache_dir: "/home/user/Documents/ProteinMPNN/stability_cache"
  proteinmpnn_dir: "/home/user/Documents/ProteinMPNN/ProteinMPNN"

data_loc:
        megascale_csv: "/media/user/DATA/raghav/Documents/ProteinMPNN/megascale_upload/Processed_K50_dG_datasets/Processed_K50_dG_datasets/Tsuboyama2023_Dataset2_Dataset3_20230416.csv"
        megascale_splits: "/media/user/DATA/raghav/Documents/ProteinMPNN/megascale_upload/mega_splits.pkl"
        megascale_pdbs: "/media/user/DATA/raghav/Documents/ProteinMPNN/megascale_upload/AlphaFold_model_PDBs/AlphaFold_model_PDBs"
        # megascale_allowlist_fasta: /home/user/Documents/ProteinMPNN/dataset-filtering/comb_train_clean.fasta
        
        fireprot_csv: "/home/user/Documents/ProteinMPNN/datasets/fireprot_upload/csvs/4_fireprotDB_bestpH.csv"
        fireprot_splits: "/home/user/Documents/ProteinMPNN/datasets/fireprot_upload/csvs/fireprot_splits.pkl"
        fireprot_pdbs: "/home/user/Documents/ProteinMPNN/datasets/fireprot_upload/pdbs"

        s669_csv: "/media/user/DATA/raghav/Documents/ProteinMPNN/Stability_benchmark_sets/s669/s669_clean_dir.csv"
        s669_pdbs: "/media/user/DATA/raghav/Documents/ProteinMPNN/Stability_benchmark_sets/s669/pdbs"

        s571_csv: "/media/user/DATA/raghav/Documents/ProteinMPNN/Stability_benchmark_sets/s571/S571.csv"
        s571_pdbs: "/media/user/DATA/raghav/Documents/ProteinMPNN/Stability_benchmark_sets/s571/pdbs"

        ssym_dir_csv: "/media/user/DATA/raghav/Documents/ProteinMPNN/Stability_benchmark_sets/ssym_dir/ssym-5fold_clean_dir.csv"
        ssym_dir_pdbs: "/media/user/DATA/raghav/Documents/ProteinMPNN/Stability_benchmark_sets/ssym_dir/pdbs"

        ssym_inv_csv: "/media/user/DATA/raghav/Documents/ProteinMPNN/Stability_benchmark_sets/ssym_inv/ssym-5fold_clean_inv.csv"
        ssym_inv_pdbs: "/media/user/DATA/raghav/Documents/ProteinMPNN/Stability_benchmark_sets/ssym_inv/pdbs"

        skempi_csv: "/media/user/DATA/raghav/Documents/ProteinMPNN/SKEMPI2/SKEMPI2_single_point_filtered.csv"
        skempi_splits: "/media/user/DATA/raghav/Documents/ProteinMPNN/SKEMPI2/skempi2_pdb_seqs_splits.pkl"
        skempi_pdbs: "/media/user/DATA/raghav/Documents/ProteinMPNN/SKEMPI2/filtered_PDBs/"